In [1]:
import torch
from torch import nn

In [2]:
m = nn.Linear(3, 3)

In [3]:
list(m.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-0.3332,  0.0516,  0.1634],
          [-0.1141, -0.3354,  0.2466],
          [ 0.2443,  0.5538, -0.0332]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.0147, 0.4376, 0.0512], requires_grad=True))]

In [4]:
x = torch.tensor([1.,2,3])

In [5]:
m(x)

tensor([0.2748, 0.3926, 1.3036], grad_fn=<ViewBackward0>)

In [6]:
w = m.weight
w

Parameter containing:
tensor([[-0.3332,  0.0516,  0.1634],
        [-0.1141, -0.3354,  0.2466],
        [ 0.2443,  0.5538, -0.0332]], requires_grad=True)

In [7]:
w.T

tensor([[-0.3332, -0.1141,  0.2443],
        [ 0.0516, -0.3354,  0.5538],
        [ 0.1634,  0.2466, -0.0332]], grad_fn=<PermuteBackward0>)

In [8]:
w.T.is_contiguous()

False

In [9]:
wt = w.T

In [10]:
# assign to module state
m.weight = nn.Parameter(wt) 
m.weight

Parameter containing:
tensor([[-0.3332, -0.1141,  0.2443],
        [ 0.0516, -0.3354,  0.5538],
        [ 0.1634,  0.2466, -0.0332]], requires_grad=True)

In [11]:
m.weight.is_contiguous()

False

In [12]:
m(x)

tensor([0.1862, 1.4799, 0.6083], grad_fn=<ViewBackward0>)

In [13]:
with torch.no_grad():
    m.weight[:] = 0

In [14]:
m.weight

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)

In [17]:
a = torch.empty((2,2))
a

tensor([[-2.9138e-01,  3.0925e-41],
        [ 0.0000e+00,  1.4013e-45]])

In [21]:
# meta tensor
a = torch.ones((10, 10), device='meta')
a

tensor(..., device='meta', size=(10, 10))

In [24]:
a[0] = torch.ones(10)
a

tensor(..., device='meta', size=(10, 10))

In [25]:
a[0]

tensor(..., device='meta', size=(10,))

In [34]:
nt = torch.nested.nested_tensor([[1.],[2.]], )
nt

nested_tensor([
  tensor([1.]),
  tensor([2.])
])

In [39]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])
c = torch.stack((a,b))
c[0] = 0
a, c

(tensor([1, 2]),
 tensor([[0, 0],
         [3, 4]]))

In [40]:
a = torch.rand(40)

print(a)

size_slices = 20
size_overlap = 10
nb_slices = 3
b = a.as_strided((nb_slices, size_slices), (size_slices-size_overlap, 1), 0)
print(b)

print(b.sum(0))

tensor([5.4208e-01, 1.9437e-01, 8.4187e-01, 2.1561e-01, 6.4671e-05, 7.5913e-01,
        7.0953e-01, 1.3022e-01, 5.0774e-01, 3.2179e-02, 5.6204e-01, 4.3706e-01,
        3.9700e-01, 5.2272e-01, 1.6539e-02, 4.5536e-02, 7.5320e-01, 3.7770e-02,
        5.0376e-01, 6.3928e-01, 6.2053e-01, 3.2952e-01, 6.5412e-01, 2.5200e-01,
        3.0689e-01, 2.1088e-01, 8.1823e-01, 1.0272e-01, 2.6544e-01, 7.6751e-01,
        3.0382e-01, 9.1469e-01, 5.1375e-01, 6.6848e-01, 6.4021e-01, 2.5999e-02,
        4.6553e-01, 3.8007e-01, 3.4215e-01, 5.3961e-01])
tensor([[5.4208e-01, 1.9437e-01, 8.4187e-01, 2.1561e-01, 6.4671e-05, 7.5913e-01,
         7.0953e-01, 1.3022e-01, 5.0774e-01, 3.2179e-02, 5.6204e-01, 4.3706e-01,
         3.9700e-01, 5.2272e-01, 1.6539e-02, 4.5536e-02, 7.5320e-01, 3.7770e-02,
         5.0376e-01, 6.3928e-01],
        [5.6204e-01, 4.3706e-01, 3.9700e-01, 5.2272e-01, 1.6539e-02, 4.5536e-02,
         7.5320e-01, 3.7770e-02, 5.0376e-01, 6.3928e-01, 6.2053e-01, 3.2952e-01,
         6.5412e-01, 2.5