In [1]:
import torch
from torch import nn

In [2]:
m = nn.Linear(3, 3)

In [3]:
list(m.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-0.3332,  0.0516,  0.1634],
          [-0.1141, -0.3354,  0.2466],
          [ 0.2443,  0.5538, -0.0332]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.0147, 0.4376, 0.0512], requires_grad=True))]

In [4]:
x = torch.tensor([1.,2,3])

In [5]:
m(x)

tensor([0.2748, 0.3926, 1.3036], grad_fn=<ViewBackward0>)

In [6]:
w = m.weight
w

Parameter containing:
tensor([[-0.3332,  0.0516,  0.1634],
        [-0.1141, -0.3354,  0.2466],
        [ 0.2443,  0.5538, -0.0332]], requires_grad=True)

In [7]:
w.T

tensor([[-0.3332, -0.1141,  0.2443],
        [ 0.0516, -0.3354,  0.5538],
        [ 0.1634,  0.2466, -0.0332]], grad_fn=<PermuteBackward0>)

In [8]:
w.T.is_contiguous()

False

In [9]:
wt = w.T

In [10]:
# assign to module state
m.weight = nn.Parameter(wt) 
m.weight

Parameter containing:
tensor([[-0.3332, -0.1141,  0.2443],
        [ 0.0516, -0.3354,  0.5538],
        [ 0.1634,  0.2466, -0.0332]], requires_grad=True)

In [11]:
m.weight.is_contiguous()

False

In [12]:
m(x)

tensor([0.1862, 1.4799, 0.6083], grad_fn=<ViewBackward0>)

In [13]:
with torch.no_grad():
    m.weight[:] = 0

In [14]:
m.weight

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)

In [17]:
a = torch.empty((2,2))
a

tensor([[-2.9138e-01,  3.0925e-41],
        [ 0.0000e+00,  1.4013e-45]])

In [21]:
# meta tensor
a = torch.ones((10, 10), device='meta')
a

tensor(..., device='meta', size=(10, 10))

In [24]:
a[0] = torch.ones(10)
a

tensor(..., device='meta', size=(10, 10))

In [25]:
a[0]

tensor(..., device='meta', size=(10,))