In [1]:
import torch
import numpy as np
import sys

In [2]:
GB = 2 ** 30
buffer = torch.ones(10 * GB, dtype=torch.int8)

In [3]:
path = 'bm.npy'
tensor = torch.from_numpy(np.lib.format.open_memmap(path))

In [4]:
path2 = 'bm2.npy'
tensor2 = torch.from_numpy(np.lib.format.open_memmap(path2))

In [5]:
%%time
buffer.copy_(tensor)

CPU times: user 22 s, sys: 1.68 s, total: 23.7 s
Wall time: 107 ms


tensor([5, 5, 5,  ..., 5, 5, 5], dtype=torch.int8)

In [6]:
buffer.copy_(tensor2)

tensor([5, 5, 5,  ..., 5, 5, 5], dtype=torch.int8)

In [7]:
buffer.pin_memory()

tensor([5, 5, 5,  ..., 5, 5, 5], dtype=torch.int8)

In [8]:
buffer *= 2

In [9]:
buffer.to('cuda')

tensor([10, 10, 10,  ..., 10, 10, 10], device='cuda:0', dtype=torch.int8)